module.exports = {
    "button": "button",
	"isPrimary": "is-primary",
	"isSecondary": "is-secondary",
    "isMarketing": "is-marketing",
    "isMarketingReverse": "is-marketing-reverse",
    "isActive": "is-active",
    "isDisabled": "is-disabled",
    "isLarge": "is-large",
    "isHalf": "is-half",
    "isSmall": "is-small",
    "colors": "colors",
    "isColorOne": "colorOne",
    "isColorTwo": "colorTwo",
    "isColorThree": "colorThree",
    "isColorFour": "colorFour",
    "isColorFive": "colorFive",
    "isColorSix": "colorSix",
    "isColorSeven": "colorSeven",
    "isColorEight": "colorEight",
    "isColorNine": "colorNine",
    "isColorTen": "colorTen",
    "isColorEleven": "colorEleven",
    "isColorTwelve": "colorTwelve",
    "isColorThirteen": "colorThirteen",
    "isColorFourteen": "colorFourteen"
}